# Generated by Django 5.0 on 2025-05-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0002_alter_customerregistration_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerregistration',
            name='audited_financials',
            field=models.FileField(blank=True, null=True, upload_to='audited_financials/'),
        ),
        migrations.AddField(
            model_name='customerregistration',
            name='balance_sheet',
            field=models.FileField(blank=True, null=True, upload_to='balance_sheets/'),
        ),
        migrations.AddField(
            model_name='customerregistration',
            name='bank_statement',
            field=models.FileField(blank=True, null=True, upload_to='bank_statements/'),
        ),
        migrations.AddField(
            model_name='customerregistration',
            name='company_certificate',
            field=models.FileField(blank=True, null=True, upload_to='company_certificates/'),
        ),
        migrations.AddField(
            model_name='customerregistration',
            name='gst_certificate',
            field=models.FileField(blank=True, null=True, upload_to='gst_certificates/'),
        ),
        migrations.AddField(
            model_name='customerregistration',
            name='kyc_document',
            field=models.FileField(blank=True, null=True, upload_to='kyc_documents/'),
        ),
        migrations.AddField(
            model_name='customerregistration',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='pan_cards/'),
        ),
        migrations.AddField(
            model_name='customerregistration',
            name='printer_report',
            field=models.FileField(blank=True, null=True, upload_to='printer_reports/'),
        ),
        migrations.AddField(
            model_name='customerregistration',
            name='security_cheques',
            field=models.FileField(blank=True, null=True, upload_to='security_cheques/'),
        ),
    ]
