# Generated by Django 5.0 on 2025-05-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0003_customerregistration_audited_financials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerregistration',
            name='billing_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customerregistration',
            name='business_start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerregistration',
            name='finance_head_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customerregistration',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerregistration',
            name='shipping_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
