from django.db import models

from django.db import models

class CustomerRegistration(models.Model):
    company_name = models.CharField(max_length=255)
    registered_address = models.CharField(max_length=255)
    pin_code = models.CharField(max_length=10)
    landline_no = models.CharField(max_length=20, blank=True, null=True)
    telefax_no = models.CharField(max_length=20, blank=True, null=True)
    finance_head_name = models.CharField(max_length=255)
    finance_head_email = models.EmailField()
    finance_head_mobile = models.CharField(max_length=20)
    billing_address1 = models.CharField(max_length=255)
    shipping_address1 = models.CharField(max_length=255)
    billing_contact_name = models.CharField(max_length=255)
    shipping_contact_name = models.CharField(max_length=255)
    billing_contact_mobile = models.CharField(max_length=20)
    shipping_contact_mobile = models.CharField(max_length=20)
    billing_contact_email = models.EmailField()
    shipping_contact_email = models.EmailField()
    pan_card_no = models.CharField(max_length=20)
    gst_no = models.CharField(max_length=20)
    msme_no = models.CharField(max_length=20, blank=True, null=True)
    cin_no = models.CharField(max_length=20, blank=True, null=True)
    company_type = models.CharField(max_length=255)  # Change from JSONField to CharField
    business_nature = models.CharField(max_length=255)  # Change from JSONField to CharField
    office_space = models.CharField(max_length=50)
    office_space_area = models.CharField(max_length=50, blank=True, null=True)
    business_start_year = models.IntegerField()
    net_worth = models.CharField(max_length=20)
    equity_capital = models.CharField(max_length=20)
    turnover_2023 = models.CharField(max_length=20)
    turnover_2022 = models.CharField(max_length=20)
    turnover_2021 = models.CharField(max_length=20)
    no_of_employees = models.IntegerField()
    no_of_branches = models.IntegerField()
    director_name1 = models.CharField(max_length=255)
    director_name2 = models.CharField(max_length=255, blank=True, null=True)
    director_address1 = models.CharField(max_length=255)
    director_email1 = models.EmailField()
    director_mobile1 = models.CharField(max_length=20)
    bank_name = models.CharField(max_length=255)
    bank_address1 = models.CharField(max_length=255)
    bank_branch_name = models.CharField(max_length=255)
    bank_signatories = models.IntegerField()
    bank_account_no = models.CharField(max_length=20)
    bank_ifsc_code = models.CharField(max_length=20)
    account_type = models.CharField(max_length=255)  # Change from JSONField to CharField
    bank_limit = models.CharField(max_length=20)
    cash_credit_limit = models.CharField(max_length=20, blank=True, null=True)
    overdraft_limit = models.CharField(max_length=20, blank=True, null=True)
    other_limit = models.CharField(max_length=20, blank=True, null=True)
    ref_name1 = models.CharField(max_length=255)
    ref_address1_1 = models.CharField(max_length=255)
    ref_telephone1 = models.CharField(max_length=20)
    ref_contact_person1 = models.CharField(max_length=255)
    ref_mobile1 = models.CharField(max_length=20)
    ref_email1 = models.EmailField()
    ref_credit_period1 = models.CharField(max_length=20)
    ref_credit_limit1 = models.CharField(max_length=20)
    signed_by = models.CharField(max_length=255)
    designation = models.CharField(max_length=255)
    office_ref_person = models.CharField(max_length=255)
    office_branch = models.CharField(max_length=255)
    office_credit_amount = models.CharField(max_length=20)
    office_credit_days = models.CharField(max_length=20)
    office_product = models.CharField(max_length=255)
    office_date = models.CharField(max_length=20)
    office_authorise_by = models.CharField(max_length=255)
    office_approved_amount = models.CharField(max_length=20)
    remark = models.TextField()

    def __str__(self):
        return self.company_name
