from django.db import models

from django.db import models

class CustomerRegistration(models.Model):
    company_name = models.CharField(max_length=255, blank=True, null=True)
    registered_address = models.CharField(max_length=255, blank=True, null=True)
    pin_code = models.CharField(max_length=10, blank=True, null=True)
    landline_no = models.CharField(max_length=20, blank=True, null=True)
    telefax_no = models.CharField(max_length=20, blank=True, null=True)
    finance_head_name = models.CharField(max_length=255, blank=True, null=True)
    finance_head_email = models.EmailField(null=True, blank=True)
    finance_head_mobile = models.CharField(max_length=20, blank=True, null=True)
    billing_address1 = models.CharField(max_length=255, blank=True, null=True)
    shipping_address1 = models.CharField(max_length=255, blank=True, null=True)
    billing_contact_name = models.CharField(max_length=255, blank=True, null=True)
    shipping_contact_name = models.CharField(max_length=255, blank=True, null=True)
    billing_contact_mobile = models.CharField(max_length=20, blank=True, null=True)
    shipping_contact_mobile = models.CharField(max_length=20, blank=True, null=True)
    billing_contact_email = models.EmailField(null=True, blank=True)
    shipping_contact_email = models.EmailField(null=True, blank=True)
    pan_card_no = models.CharField(max_length=20, blank=True, null=True)
    gst_no = models.CharField(max_length=20, blank=True, null=True)
    msme_no = models.CharField(max_length=20, blank=True, null=True)
    cin_no = models.CharField(max_length=20, blank=True, null=True)
    company_type = models.CharField(max_length=255, blank=True, null=True)  # Change from JSONField to CharField
    business_nature = models.CharField(max_length=255, blank=True, null=True)  # Change from JSONField to CharField
    office_space = models.CharField(max_length=50, blank=True, null=True)
    office_space_area = models.CharField(max_length=50, blank=True, null=True)
    business_start_year = models.IntegerField(null=True, blank=True)
    net_worth = models.CharField(max_length=20, blank=True, null=True)
    equity_capital = models.CharField(max_length=20, blank=True, null=True)
    turnover_2023 = models.CharField(max_length=20, blank=True, null=True)
    turnover_2022 = models.CharField(max_length=20, blank=True, null=True)
    turnover_2021 = models.CharField(max_length=20, blank=True, null=True)
    no_of_employees = models.IntegerField(null=True, blank=True)
    no_of_branches = models.IntegerField(null=True, blank=True)
    director_name1 = models.CharField(max_length=255, blank=True, null=True)
    director_name2 = models.CharField(max_length=255, blank=True, null=True)
    director_address1 = models.CharField(max_length=255, blank=True, null=True)
    director_email1 = models.EmailField(blank=True, null=True)
    director_mobile1 = models.CharField(max_length=20, blank=True, null=True)
    bank_name = models.CharField(max_length=255, blank=True, null=True)
    bank_address1 = models.CharField(max_length=255, blank=True, null=True)
    bank_branch_name = models.CharField(max_length=255, blank=True, null=True)
    bank_signatories = models.IntegerField(null=True, blank=True)
    bank_account_no = models.CharField(max_length=20, blank=True, null=True)
    bank_ifsc_code = models.CharField(max_length=20, blank=True, null=True)
    account_type = models.CharField(max_length=255, blank=True, null=True)  # Change from JSONField to CharField
    bank_limit = models.CharField(max_length=20, blank=True, null=True)
    cash_credit_limit = models.CharField(max_length=20, blank=True, null=True)
    overdraft_limit = models.CharField(max_length=20, blank=True, null=True)
    other_limit = models.CharField(max_length=20, blank=True, null=True)
    ref_name1 = models.CharField(max_length=255, blank=True, null=True)
    ref_address1_1 = models.CharField(max_length=255, blank=True, null=True)
    ref_telephone1 = models.CharField(max_length=20, blank=True, null=True)
    ref_contact_person1 = models.CharField(max_length=255, blank=True, null=True)
    ref_mobile1 = models.CharField(max_length=20, blank=True, null=True)
    ref_email1 = models.EmailField(blank=True, null=True)
    ref_credit_period1 = models.CharField(max_length=20, blank=True, null=True)
    ref_credit_limit1 = models.CharField(max_length=20, blank=True, null=True)
    signed_by = models.CharField(max_length=255, blank=True, null=True)
    designation = models.CharField(max_length=255, blank=True, null=True)
    office_ref_person = models.CharField(max_length=255, blank=True, null=True)
    office_branch = models.CharField(max_length=255, blank=True, null=True)
    office_credit_amount = models.CharField(max_length=20, blank=True, null=True)
    office_credit_days = models.CharField(max_length=20, blank=True, null=True)
    office_product = models.CharField(max_length=255, blank=True, null=True)
    office_date = models.CharField(max_length=20, blank=True, null=True)
    office_authorise_by = models.CharField(max_length=255, blank=True, null=True)
    office_approved_amount = models.CharField(max_length=20, blank=True, null=True)
    vendor_photo = models.FileField(upload_to='vendor_photo/', null=True, blank=True)
    printer_report = models.FileField(upload_to='printer_reports/', null=True, blank=True)
    gst_certificate = models.FileField(upload_to='gst_certificates/', null=True, blank=True)
    pan_card = models.FileField(upload_to='pan_cards/', null=True, blank=True)
    balance_sheet = models.FileField(upload_to='balance_sheets/', null=True, blank=True)
    company_certificate = models.FileField(upload_to='company_certificates/', null=True, blank=True)
    bank_statement = models.FileField(upload_to='bank_statements/', null=True, blank=True)
    audited_financials = models.FileField(upload_to='audited_financials/', null=True, blank=True)
    kyc_document = models.FileField(upload_to='kyc_documents/', null=True, blank=True)
    security_cheques = models.FileField(upload_to='security_cheques/', null=True, blank=True)
   
    remark = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.company_name
